-- 코드를 입력하세요
# SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
# FROM REST_INFO 
# GROUP BY FOOD_TYPE
# ORDER BY FOOD_TYPE DESC
# 이렇게 하면 테이블에서 가장 상단의 식당 정보를 가져오게 됨(쿼리 진행순서때문)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC