# SELECT P.PRODUCT_CODE, SUM(P.PRICE*O.AMOUNT) AS SALES
# FROM PRODUCT AS P
# LEFT JOIN 
#     (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
#     FROM OFFLINE_SALE
#     GROUP BY PRODUCT_ID
#     ORDER BY PRODUCT_ID) AS O
# ON P.PRODUCT_CODE = O.PRODUCT_ID   
# ORDER BY SALES DESC, P.PRODUCT_CODE


-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(O.SALES_AMOUNT*P.PRICE) AS SALES
FROM PRODUCT AS P
    LEFT JOIN OFFLINE_SALE AS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE
# O.SALES_AMOUNT*P.PRICE AS SALES