-- 코드를 작성해주세요
SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS C
LEFT JOIN ECOLI_DATA AS P
ON C.PARENT_ID=P.ID
WHERE C.PARENT_ID IS NOT NULL AND P.GENOTYPE & C.GENOTYPE =P.GENOTYPE
ORDER BY C.ID